# Generated by Django 5.1.5 on 2026-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_alter_incidents_incidenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.URLField(blank=True, help_text='Supabase storage URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='file',
            field=models.URLField(blank=True, help_text='Supabase storage URL', max_length=500, null=True),
        ),
    ]
