# Generated by Django 5.1.5 on 2026-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_analyzer', '0003_potholeanalysis_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholeanalysis',
            name='image',
            field=models.URLField(help_text='Supabase storage URL for original image', max_length=500),
        ),
        migrations.AlterField(
            model_name='potholeanalysis',
            name='processed_image',
            field=models.URLField(blank=True, help_text='Supabase storage URL for processed image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='potholevideoanalysis',
            name='processed_video',
            field=models.URLField(blank=True, help_text='Supabase storage URL for processed video', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='potholevideoanalysis',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Supabase storage URL for thumbnail', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='potholevideoanalysis',
            name='video',
            field=models.URLField(help_text='Supabase storage URL for original video', max_length=500),
        ),
        migrations.AlterField(
            model_name='videoframedetection',
            name='frame_image',
            field=models.URLField(blank=True, help_text='Supabase storage URL for frame image', max_length=500, null=True),
        ),
    ]
